// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error único de aplicación: invariantes de dominio + fallos de repositorio.
 * Serializable para el frontend; tipo TS generado por ts-rs.
 */
export type AppError = { "kind": "ProjectNameEmpty" } | { "kind": "TaskNameEmpty" } | { "kind": "NotFound", "detail": string } | { "kind": "Repository", "detail": string };
