// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeSessionDto = { id: string, taskId: string, startedAt: number, endedAt: number | null, lastHeartbeatAt: number | null, isSuspect: boolean, };
