// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDto = { id: string, name: string, color: string | null, createdAt: number, archived: boolean, };
